(import (rnrs)
	(rnrs eval)
	(util file)
	(util port)
	(sagittarius)
	(srfi :64))

(test-begin "SRFI library names")

(define srfi-data (string-append (current-directory) "/test/data/srfi-data.scm"))

(define (test-srfi-name data)
  (define number (cadr (assq 'number data)))
  (define library-name (cond ((assq 'library-name data) => cadr)
			     (else #f)))
  (define (supported? n)
    (guard (e (else #f))
      (eval `(import (srfi ,n)) (environment '(sagittarius)))))
  (when (and library-name (supported? number))
    ;; check if we support srfi itself
    (let ((name (read (open-string-input-port
		       (format "(srfi :~a ~a)" number library-name)))))
      (test-assert name (eval `(import ,name) (environment '(sagittarius)))))))

(call-with-input-file srfi-data
  (lambda (p)
    (port-for-each test-srfi-name (lambda () (read p)))))

;; srfi 226 has different names between R6RS and R7RS
;; and unfortunately, it's not listed in srfi-data.scm (even the latest version)
(define library-names
  '((srfi :226 control prompts)
    (srfi 226 prompt)
    (srfi :226 control continuations)
    (srfi 226 continuation)
    (srfi :226 control shift-reset)
    (srfi 226 shift-reset)
    (srfi :226 control inspection)
    (srfi 226 inspection)
    (srfi :226 control continuation-marks)
    (srfi 226 continuation-mark)
    (srfi :226 control parameters)
    (srfi 226 parameter)
    (srfi :226 control fluids)
    (srfi 226 fluid)
    (srfi :226 control call-in-initial-continuation)
    (srfi 226 call-in-initial-continuation)
    (srfi :226 control promises)
    (srfi 226 promise)
    (srfi :226 control exceptions)
    (srfi 226 exception)
    (srfi :226 control conditions)
    (srfi 226 condition)
    (srfi :226 control times)
    (srfi 226 time)
    (srfi :226 control threads)
    (srfi 226 thread)
    (srfi :226 control thread-locals)
    (srfi 226 thread-local)
    (srfi :226 control interrupts)
    (srfi 226 interrupt)))
(define (test-library name)
  (test-assert name (eval `(import ,name) (environment '(sagittarius)))))
(for-each test-library library-names)


(test-end)
