(import (rnrs)
	(sagittarius pty)
	(sagittarius stty)
	(sagittarius pam)
	(sagittarius process)
	(srfi :18))

(define (run-output-reader out)
  (thread-start!
   (make-thread (lambda ()
		  (let loop ()
		    (let ((u8 (get-u8 out)))
		      (put-u8 (standard-output-port) u8)
		      (flush-output-port (standard-output-port))
		      (loop)))))))

(define (prompts-handler prompts)
  (define (prompt-handler prompt)
    (display (cdr prompt)) (flush-output-port (current-output-port))
    (if (eq? (car prompt) 'echo-off)
	(with-stty '((not echo) echonl) 
         (lambda () (get-line (current-input-port))))
        (get-line (current-input-port))))
  (vector-map prompt-handler prompts))


(cond ((pam-authenticate "login" "yo32es" prompts-handler) =>
       (lambda (token)
	 (define pty (make-pty))
	 (print token)
	 (pty-spawn! pty "/bin/bash" '() :token token)
	 (pty-resize! pty 167 64)
	 (run-output-reader (pty-input-port pty))
	 (let ((in (pty-output-port pty)))
	   (let loop ()
	     (let ((u8 (get-u8 (standard-input-port))))
	       (unless (eof-object? u8)
		 (put-u8 in u8)
		 (loop)))))))
      (else (error 'who "authentication failed")))
  
