(import (rnrs)
	(sagittarius socket)
	(srfi :18))

(define s* (make-server-socket* "9999"))
(define selector (make-socket-selector))
(for-each (lambda (s) (socket-selector-add! selector s)) s*)

(define (accept srv)
  (print srv)
  (let ((s (socket-accept srv)))
    (socket-send s (socket-recv s 255))
    (socket-shutdown s SHUT_RDWR)
    (socket-close s)))

(define thread (make-thread
		(lambda ()
		  (let loop ()
		    (let-values (((s* t*) (socket-selector-wait! selector)))
		      (for-each accept (map car s*))
		      (unless (zero? (socket-selector-size selector))
			(loop)))))))
(thread-start! thread)
(define (server-service sock)
  (number->string (socket-info-port (socket-info sock))))
(define (check service ai-family)
  (let ((s (make-client-socket "localhost" service ai-family)))
    (socket-send s (string->utf8 "hello"))
    (print (utf8->string (socket-recv s 255)))))

(for-each check (map server-service s*) (list AF_INET AF_INET))
