(import (rnrs)
	(sagittarius control)
	(rfc zlib))
(call-with-port
    (open-file-input-port "ext/zlib/data/compressed-1.bin" (file-options) 'block)
  (lambda (in)
      (define din (open-inflating-input-port in))
      (let ((bv (get-bytevector-all din)))
	(close-port din)
	bv))
  #;(lambda (fin)
    (let-values (((out e) (open-bytevector-output-port)))
      (let ((dout (open-inflating-output-port (standard-output-port))))
	(put-bytevector dout (get-bytevector-all fin))
	(close-port dout)
	(e)))))
