YPSILON_HOME="D:/Program Files/Ypsilon"
PROG=Ypsilon --sitelib=$(YPSILON_HOME)/sitelib

all: ucd-1 ucd-2 ucd-code lexeme-code

ucd-1:
	@echo build-ucd-1; $(PROG) build-ucd-1.scm
ucd-2:
	@echo build-ucd-2; $(PROG) build-ucd-2.scm
ucd-code:
	@echo build-ucd-code; $(PROG) build-ucd-code.scm
lexeme-code:
	@echo build-lexeme-code; $(PROG) build-lexeme-code.scm
