PROG=sash

all: ucd-1 ucd-2 ucd-code lexeme-code charset

ucd-1:
	@echo build-ucd-1; $(PROG) build-ucd-1.scm
ucd-2:
	@echo build-ucd-2; $(PROG) build-ucd-2.scm
ucd-code:
	@echo build-ucd-code; $(PROG) build-ucd-code.scm
lexeme-code:
	@echo build-lexeme-code; $(PROG) build-lexeme-code.scm
charset:
	@echo build-charset; $(PROG) build-charset.scm