/* This file is automatically generated by builtin-keywords.scm. DO NOT EDIT! */
#ifndef BUILTIN_KEYWORD_H__
#define BUILTIN_KEYWORD_H__
SG_EXTERN SgSymbol Sg_BuiltinKeywords[];
#define SG_KEYWORD_LAMBDA_LIST SG_OBJ(&Sg_BuiltinKeywords[0])
#define SG_KEYWORD_QUALIFIER SG_OBJ(&Sg_BuiltinKeywords[1])
#define SG_KEYWORD_SPECIALIZERS SG_OBJ(&Sg_BuiltinKeywords[2])
#define SG_KEYWORD_GENERIC SG_OBJ(&Sg_BuiltinKeywords[3])
#define SG_KEYWORD_PROCEDURE SG_OBJ(&Sg_BuiltinKeywords[4])
#define SG_KEYWORD_DEFINITION_NAME SG_OBJ(&Sg_BuiltinKeywords[5])
#define SG_KEYWORD_PRIMARY SG_OBJ(&Sg_BuiltinKeywords[6])
#define SG_KEYWORD_BEFORE SG_OBJ(&Sg_BuiltinKeywords[7])
#define SG_KEYWORD_AFTER SG_OBJ(&Sg_BuiltinKeywords[8])
#define SG_KEYWORD_AROUND SG_OBJ(&Sg_BuiltinKeywords[9])
#define SG_KEYWORD_INIT_VALUE SG_OBJ(&Sg_BuiltinKeywords[10])
#define SG_KEYWORD_INIT_KEYWORD SG_OBJ(&Sg_BuiltinKeywords[11])
#define SG_KEYWORD_ALL SG_OBJ(&Sg_BuiltinKeywords[12])
#define SG_KEYWORD_EXPORT_READER_MACRO SG_OBJ(&Sg_BuiltinKeywords[13])
#endif /* BUILTIN_KEYWORD_H__ */
