#!read-macro=sagittarius/bv-string
(import (rnrs)
        (net socket)
        (net server)
        (net http-server)
        (srfi :18)
        (srfi :64))

(test-begin "net/http-server")

(define (recv-text sock)
  (socket-set-read-timeout! sock 1000)
  (let loop ((acc '()))
    (guard (e ((socket-read-timeout-error? e)
               (apply string-append (reverse acc)))
              ((socket-closed-error? e)
               (apply string-append (reverse acc))))
      (let ((bv (socket-recv sock 8192)))
        (if (and bv (bytevector? bv) (> (bytevector-length bv) 0))
            (loop (cons (utf8->string bv) acc))
            (apply string-append (reverse acc)))))))

(define (contains? s part)
  (let ((n (string-length s))
        (m (string-length part)))
    (let loop ((i 0))
      (cond ((> (+ i m) n) #f)
            ((string=? (substring s i (+ i m)) part) #t)
            (else (loop (+ i 1)))))))

(let ()
  (define (app req res)
    (http-server:response-status-set! res 201)
    (http-server:response-header-set! res "x-test" "ok")
    (http-server:response-text! res "created")
    res)
  (define server (make-http-server "0" app))
  (server-start! server :background #t)
  (thread-sleep! 0.2)
  (let ((sock (make-client-socket "localhost" (server-port server))))
    (socket-send sock (string->utf8 "GET / HTTP/1.1\r\nHost: localhost\r\n\r\n"))
    (let ((txt (recv-text sock)))
      (test-assert "status 201" (contains? txt "HTTP/1.1 201 Created"))
      (test-assert "custom header" (contains? txt "x-test: ok"))
      (test-assert "body" (contains? txt "created")))
    (socket-close sock))
  (server-stop! server))

(let* ((router (make-http-server:router)))
  (http-server:router-add-route!
   router
   'GET
   "/hello/:name"
   (lambda (req res)
     (http-server:response-text!
      res
      (string-append "hello " (http-server:request-attribute-ref req 'name "?")))))
  (let* ((app (http-server:make-router-handler router))
         (server (make-http-server "0" app)))
  (server-start! server :background #t)
  (thread-sleep! 0.2)
  (let ((sock (make-client-socket "localhost" (server-port server))))
    (socket-send sock (string->utf8 "GET /hello/sagittarius HTTP/1.1\r\nHost: localhost\r\n\r\n"))
    (let ((txt (recv-text sock)))
      (test-assert "router path var" (contains? txt "hello sagittarius")))
    (socket-close sock))
  (server-stop! server)))

(let ()
  (define count 0)
  (define (app req res)
    (set! count (+ count 1))
    (http-server:response-cacheable?-set! res #t)
    (http-server:response-cache-ttl-set! res 10)
    (http-server:response-text! res (string-append "count=" (number->string count)))
    res)
  (define config
    (make-http-server-config
     :cache (make-http-server:memory-cache :capacity 16)))
  (define server (make-http-server "0" app :config config))
  (server-start! server :background #t)
  (thread-sleep! 0.2)
  (let ((sock1 (make-client-socket "localhost" (server-port server)))
        (sock2 (make-client-socket "localhost" (server-port server))))
    (socket-send sock1 (string->utf8 "GET /cached HTTP/1.1\r\nHost: localhost\r\n\r\n"))
    (let ((txt1 (recv-text sock1)))
      (test-assert "first response" (contains? txt1 "count=1")))
    (socket-send sock2 (string->utf8 "GET /cached HTTP/1.1\r\nHost: localhost\r\n\r\n"))
    (let ((txt2 (recv-text sock2)))
      (test-assert "second response from cache" (contains? txt2 "count=1")))
    (socket-close sock1)
    (socket-close sock2))
  (test-equal "handler invoked once" 1 count)
  (server-stop! server))

(let ()
  (define (app req res)
    (http-server:response-text! res (http-server:request-path req))
    res)
  (define server (make-http-server "0" app))
  (server-start! server :background #t)
  (thread-sleep! 0.2)
  (let ((sock (make-client-socket "localhost" (server-port server))))
    (socket-send sock (string->utf8 "GET /a HTTP/1.1\r\nHost: localhost\r\n\r\n"))
    (let ((txt1 (recv-text sock)))
      (test-assert "first response status" (contains? txt1 "HTTP/1.1 200 OK"))
      (test-assert "first response body" (contains? txt1 "/a")))
    (socket-close sock))
  (server-stop! server))

(let ()
  (define (app req res)
    (http-server:response-text! res "ok")
    res)
  (define server (make-http-server "0" app))
  (server-start! server :background #t)
  (thread-sleep! 0.2)
  (let ((sock (make-client-socket "localhost" (server-port server))))
    (socket-send sock (string->utf8 "POST /c HTTP/1.1\r\nHost: localhost\r\nTransfer-Encoding: chunked\r\n\r\n4\r\ntest\r\n0\r\n\r\n"))
    (let ((txt (recv-text sock)))
      (test-assert "chunked accepted" (contains? txt "HTTP/1.1 200 OK")))
    (socket-close sock))
  (server-stop! server))

(test-end)
