name: Document release

on:
  workflow_dispatch:
    inputs:
      buildId:
        description: "Release build ID"
        required: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download document artifact
        uses: actions/download-artifact@v8
        with:
          run-id: ${{ inputs.buildId }}
          pattern: sagittarius-doc-*
          path: _docs
      - name: Setup pages
        uses: actions/configure-pages@v6
      - name: Debug
        run: |
          ls -lt _docs
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: _docs
      - name:
        id: deployment
        uses: actions/deploy-pages@v5
