name: Sagittarius PR build
on:
  pull_request:
    branches: [ master ]

jobs:
  POSIX-Build:
    uses: ./.github/workflows/posix-build.yml
  Windows-Build:
    uses: ./.github/workflows/windows-build.yml
  VMActions-Build:
    uses: ./.github/workflows/vmactions-build.yml
  POSIX-Build-generic:
    needs: POSIX-Build
    uses: ./.github/workflows/posix-build.yml
    with:
      options: -DENFORCE_GENERIC_SELECTOR=ON


