name: Builds using VM Actions
on: workflow_call

jobs:
  VMActions-Build:
    runs-on: ubuntu-latest
    name: ${{ matrix.config.name }} - ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          # - aarch64
        config:
          - { name: 'freebsd', setup: '.ci/setup-freebsd.sh' }
          - { name: 'openbsd', setup: '.ci/setup-openbsd.sh' }
          - { name: 'netbsd',  setup: '.ci/setup-netbsd.sh', cc: '.ci/cc-netbsd.sh' }
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build and test
        uses: ./.github/actions/vmactions-build
        with:
          vm-name: ${{ matrix.config.name }}
          arch: ${{ matrix.arch }}
          setup-script: ${{ matrix.config.setup }}
