name: Windows Build
on: workflow_call

jobs:
  Windows-Build:
    runs-on: ${{ matrix.images }}
    name: ${{ matrix.images }} - ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, x86]
        images: [windows-2022, windows-2025]
    steps:
      - name: Build and test
        uses: ./.github/actions/windows-build
        with:
          arch: ${{ matrix.arch }}
          checkout-path: target
